name: Daily WNBA Data Update
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: dev-automation

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run full update script
        # Use the new script
        run: python run_data_updates.py

      - name: Pull latest changes to avoid push conflicts
        run: git pull origin dev-automation

      - name: Commit and push if data changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated Daily Data Update"
          branch: dev-automation
          file_pattern: 'database/*.csv database/*.json'
