name: Hourly WNBA Injury Update
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-injuries:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: dev-automation

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run injury-only update
        # Use the new script with the --injuries flag
        run: python run_data_updates.py --injuries

      - name: Pull latest changes to avoid push conflicts
        run: git pull origin dev-automation
        
      - name: Commit and push if data changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated Hourly Injury Update"
          branch: dev-automation
          file_pattern: 'database/live_injuries.json'
