name: ✅ Hourly WNBA Injury Update
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  update-injuries:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: dev-automation

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run injury-only update
        run: python update_databases.py --injuries-only
        
      - name: Commit and push if data changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated Hourly Injury Update"
          branch: dev-automation
          file_pattern: 'database/live_injuries.json'
          token: ${{ secrets.GITHUB_TOKEN }}
