# .github/workflows/your-hourly-injury-workflow.yml

name: Hourly WNBA Injury Update
on:
  schedule:
    - cron: '0 * * * *' # Runs at the top of every hour
  workflow_dispatch:

jobs:
  update-injuries:
    runs-on: ubuntu-latest

    # FIX: Grant write permissions to the job for pushing commits
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: dev-automation

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run injury-only update
        run: python update_databases.py --injuries-only

      - name: Commit and push if data changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated Hourly Injury Update"
          branch: dev-automation
          file_pattern: 'database/live_injuries.json'
          # FIX: The 'token' input is unnecessary and has been removed.
